#-   id: go-vet
#    name: go vet
#    description: Runs `go vet`, requires golang
#    entry: go-vet.sh
#    language: script
-   id: go-vet
    name: 'go vet'
    entry: go-vet.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `go vet`, requires golang"
